language: python
python:
  -  "3.8"
install:
  - pip install -r requirements.txt
env:
  -  APP_SETTINGS=config.DevelopmentConfig DATABASE_URL=postgresql://USERNAME:PASSWORD@localhost/DBNAME
script:
  - python -m pytest -v
  