language: python
python:
  -  "3.8"
install:
  - pip install -r requirements.txt
  - pip install codecov
env:
  - APP_SETTINGS=config.DevelopmentConfig DATABASE_URL=postgresql://USERNAME:PASSWORD@localhost/DBNAME # CODECOV_TOKEN="b2ffc986-a1ac-48ef-87c3-270a572a3ced"
script:
  - python -m pytest -v
after_success:
  - codecov