openapi: 3.0.2
info:
  title: "Swagger Auth, validate and user permission"
  version: 1.0.0
paths:
  /auth:
    post:
      tags: 
        - "Auth and Valid"
      summary: "Authentication"
      description: "Create token and get it"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                login:
                  type: "string"
                password:
                  type: "string"
            example:
              login: "a1pha1337@gmail.com"
              password: "rhokef3"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: "string"
              example: "f57ebe597a3741b688269209fa29b053"
        401:
          description: "Incorrect login/pass"
          content: {}
          
  /validate/{token}:
    get:
      tags: 
        - "Auth and Valid"
      summary: "Validation"
      description: "Send token and check it"
      parameters:
      - name: "token"
        in: "path"
        description: "User token"
        required: true
        schema:
          type: "string"
      responses:
        200:
          description: "OK"
        404:
          description: "Non-existing token"
          
  /register:
    post:
      tags:
        - "User Info"
      summary: "Register user"
      description: "Register user and get session token"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                login:
                  type: "string"
                password:
                  type: "string"
            example:
              login: "a1pha1337@gmail.com"
              password: "rhokef3"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: "string"
              example: "f57ebe597a3741b688269209fa29b053"
        400:
          description: "Incorrect login/pass"
          content: {}
          
  /deleteUser/{token}:
    delete:
      tags:
        - "User Info"
      summary: "Delete user himself"
      description: ""
      parameters:
      - name: "token"
        in: "path"
        description: "User token"
        required: true
        schema:
          type: "string"
      responses:
        200:
          description: "OK"
        404:
          description: "Non-existing token"
          
  /deleteUserTarget:
    delete:
      tags:
        - "User Info"
      summary: "Delete target user"
      description: "Send your token and user ID of user you want to delete"
      parameters:
      - name: "token"
        in: "query"
        description: "User token"
        required: true
        schema:
          type: "string"
      - name: "userID"
        in: "query"
        description: "ID of user you want to delete"
        required: true
        schema:
          type: "string"
      responses:
        200:
          description: "OK"
        400:
          description: "Non-existing user ID"
        404:
          description: "Non-existing token"

  /GetUserInfo/{token}:
    get:
      tags: 
      - "User Info"
      summary: "Get user info"
      description: ""
      parameters: 
      - name: "token"
        in: "path"
        description: "User token"
        schema:
          type: "string"
        required: true
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  UserID:
                    type: "integer"
                    format: "int64"
                  Login:
                    type: "string"
                  Name:
                    type: "string"
              example:
                UserID: "0"
                Login: "alpha13371@mail.ru"
                Name: "Solo_228"
        404:
          description: "Non-existing token"
          
  /GetUserPublicInfo/{login}:
    get:
      tags: 
      - "User Info"
      summary: "Get user public info"
      description: ""
      parameters: 
      - name: "login"
        in: "path"
        description: "User login"
        schema:
          type: "string"
        required: true
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  UserID:
                    type: "integer"
                    format: "int64"
                  Login:
                    type: "string"
                  Name:
                    type: "string"
              example:
                UserID: "0"
                Login: "alpha13371@mail.ru"
                Name: "Solo_228"
        404:
          description: "Non-existing token"
          
  /EditUserInfo:
    put:
      tags: 
      - "User Info"
      summary: "Edit user info (himself)"
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                token:
                  type: "string"
                login:
                  type: "string"
                password:
                  type: "string"
                name: 
                  type: "string"
            example:
              token: "f57ebe597a3741b688269209fa29b053"
              login: "a1pha1337@gmail.com"
              password: "rhokef3"
              name: "Solo_322"
      responses:
        200:
          description: "OK"
        404:
          description: "Non-existing token"
      
  /getUserPermissions/{user_id}:
    get:
      tags:
        - "Permissions"
      summary: "Gets user permissions"
      description: "Gets user permissions by user ID"
      parameters:
      - name: "user_id"
        in: path
        description: "User ID"
        required: true
        schema:
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "object"
                  properties:
                    CollectionID:
                      type: "integer"
                      format: "int64"
                    Permissions:
                      type: "object"
                      properties:
                        Read:
                          type: "boolean"
                        Write:
                          type: "boolean"
                        Edit others:
                          type: "boolean"
                        Share:
                          type: "boolean"
                        Delete post:
                          type: "boolean"
                        Delete collection:
                          type: "boolean"
                        Delete user from collection:
                          type: "boolean"
              example: 
                - collection_id: "228"
                  permissions:
                    read: true
                    write: false
                    edit_others: false
                    share: false
                    delete_post: false
                    delete_collection: false
                    delete_user_from_collection: false
                - collection_id: "322"
                  permissions:
                    read: true
                    write: true
                    edit_others: true
                    share: true
                    delete_post: true
                    delete_collection: false
                    delete_user_from_collection: false
        404:
          description: "Not ok"
    
  /editUserPermissions:
    put:
      tags:
        - "Permissions"
      summary: "Edit user permissions"
      description: "Edit user permissions by user ID and token"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                token:
                  type: "string"
                user_id:
                  type: "integer"
                  format: "int64"
                Permissions:
                      type: "object"
                      properties:
                        Read:
                          type: "boolean"
                        Write:
                          type: "boolean"
                        Edit others:
                          type: "boolean"
                        Share:
                          type: "boolean"
                        Delete post:
                          type: "boolean"
                        Delete collection:
                          type: "boolean"
                        Delete user from collection:
                          type: "boolean"
      responses:
        200:
          description: "OK"
        400:
          description: "Access error"
        404:
          description: "Non-existing token"
