openapi: 3.0.2
info:
  title: "Swagger Auth, validate and user permission"
  version: 1.0.0
paths:
  /auth:
    post:
      summary: "Authentication"
      description: "Create token and get it"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                login:
                  type: "string"
                password:
                  type: "string"
            example:
              login: "a1pha1337@gmail.com"
              password: "rhokef3"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: "string"
              example: f57ebe597a3741b688269209fa29b053
        400:
          description: "Incorrect login/pass"
          content: {}
  /validate/{token}:
    get:
      summary: "Validation"
      description: "Send token and check it"
      parameters:
      - name: "token"
        in: "path"
        description: "User token"
        required: true
        schema:
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "OK"
